version: '3.8'
services:
  redis:
    image: redis:7-alpine
    container_name: pelajarin_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    networks:
      - pelajarin_network

volumes:
  redis_data:
    driver: local

networks:
  pelajarin_network:
    driver: bridge
