"""Add content_blocks and summary to sub_topics

Revision ID: fe42b2a828b7
Revises: 20250727_add_performance_indexes
Create Date: 2025-07-27 21:11:32.438506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe42b2a828b7'
down_revision: Union[str, Sequence[str], None] = '20250727_add_performance_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_topics', sa.Column('content_blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sub_topics', sa.Column('summary_for_next_topic', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_topics', 'summary_for_next_topic')
    op.drop_column('sub_topics', 'content_blocks')
    # ### end Alembic commands ###
